export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'About',
    headline: 'Lorem ipsum dolor sit amet. ',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis at consectetur lorem donec massa. Eu tincidunt tortor aliquam nulla. A cras semper auctor neque vitae tempus quam.',
    buttonLabel: 'Get started',
    imgStart: true,
    img: require('../../images/svg-1.svg'),
    alt: 'image',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjTwo = {
    id: 'offer',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Offer',
    headline: 'Lorem ipsum dolor sit amet. ',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis at consectetur lorem donec massa. Eu tincidunt tortor aliquam nulla. A cras semper auctor neque vitae tempus quam.',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/svg-3.svg'),
    alt: 'image',
    dark: false,
    primary: false,
    darkText: true,
}

export const homeObjThree = {
    id: 'signup',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Join us',
    headline: 'Lorem ipsum dolor sit amet. ',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis at consectetur lorem donec massa. Eu tincidunt tortor aliquam nulla. A cras semper auctor neque vitae tempus quam.',
    buttonLabel: 'Get started',
    imgStart: true,
    img: require('../../images/svg-1.svg'),
    alt: 'image',
    dark: true,
    primary: true,
    darkText: false,
}